services:
  gitlab:
    image: gitlab/gitlab-ce:17.2.2-ce.0
    container_name: gitlab
    restart: always
    hostname: 'domain.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        # Add any other gitlab.rb configuration here, each on its own line
        external_url 'http://domain.com'
        gitlab_rails['registry_enabled'] = true
        registry_external_url 'http://domain.com:5001'
    ports:
      - '0.0.0.0:80:80'
      - '0.0.0.0:443:443'
      - '0.0.0.0:24:22'
      - '0.0.0.0:5001:5001'
    volumes:
      - './config:/etc/gitlab'
      - './logs:/var/log/gitlab'
      - './data:/var/opt/gitlab'

