services:
  mc-forge:
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
    volumes:
      - ./:/data  # Подключите папку с сервером
    environment:
      EULA: "TRUE"
      TYPE: "FORGE"
      VERSION: "1.20.1"
      FORGE_VERSION: "47.4.0"
